### ISSUE TITLE
Why is the official website only in English, why doesn’t it support Chinese?

### ISSUE THREAD

**Issue by wxw9868** [goplus/gop#1792]
### Proposal

官网为啥是英文的，作为国人开发的语言，而且是服务国人的，并且还服务于儿童编程，怎么不支持中文呢。只有英文这很难让人理解啊。难道开发团队都是外国人？还是说开发团队不愿意支持中文？或者难道有什么特殊的原因？

### Background

官网为啥是英文的，作为国人开发的语言，而且是服务国人的，并且还服务于儿童编程，怎么不支持中文呢。只有英文这很难让人理解啊。难道开发团队都是外国人？还是说开发团队不愿意支持中文？或者难道有什么特殊的原因？

### Workarounds

官网为啥是英文的，作为国人开发的语言，而且是服务国人的，并且还服务于儿童编程，怎么不支持中文呢。只有英文这很难让人理解啊。难道开发团队都是外国人？还是说开发团队不愿意支持中文？或者难道有什么特殊的原因？

**Comment by wxw9868** [comment]
期望详细解惑

**Comment by xushiwei** [comment]
It's just a matter of team energy. Because we can't divide our energy to maintain two documents at the same time, we temporarily chose English, which is more widely accepted around the world. In the future we will provide documentation in all languages, including Chinese.

只是团队精力的问题，因为分不出精力同时维护2份文档，所以暂时选择了从全球接受度更广的英文。未来我们会提供所有语言都支持的文档，包括中文。
